version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
    ports:
      - "8082:5000"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
