apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      #version: v1
  template:
    metadata:
      labels:
        app: webapp
        #version: v1
    spec:
      containers:
      - name: webapp
        image: nasrulhm/demo:v1
        #image: nasrulhm/demo:v2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
    #version: v1
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 5000
      nodePort: 31321
  type: LoadBalancer
